---
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
production:
  :concurrency: 1
  :verbose: false
  :pidfile: <%= File.join(ENV.fetch('PIDS_PATH', 'tmp'),'hullsyncsidekiq.pid') %>
development:
  :verbose: true
:queues:
  - crosswalk
  - gush
  - workflow_monitor
  - transfer_workflow_monitor
  - inform_user
#  - default
